
[
        {
            "name":"Default",
            "feed":0.055,
            "kill":0.062,
            "biasStrength":0
        },
        {
            "name":"Mitosis",
            "feed":0.0367,
            "kill":0.0649,
            "biasStrength":0
        },
        {
            "name":"Coral",
            "feed":0.0545,
            "kill":0.062,
            "biasStrength":0
        },
        {
            "name":"Biased",
            "feed":0.035,
            "kill":0.064,
            "biasStrength":0.005
        },
        {
            "name":"Nameplate",
            "feed":0.035,
            "kill":0.063,
            "biasStrength":0.01
        },
        {
            "name":"NameplateFinal",
            "feed":0.05,
            "kill":0.061,
            "biasStrength":0.007
        }
]
